# Default values for my-apl-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

AppImage: southamerica-east1-docker.pkg.dev/gothic-space-454920-b4/calculator-image/addition:latest
replicaCount: 1
AplName: my-apl
svcType: NodePort
containerPort: 8080
Port: 80
NodePort: 30000
deployment:
  env:
    - name: HELLO_SVC_TYPE
      value: "values.yaml"
service:
  AlbScheme: internet-facing
