apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .values.AplName }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .values.service.AlbScheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/HealthCheckProtocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: {{ .values.AplName }}
            port:
              number: {{ .values.Port }}
        pathType: Prefix
