apiVersion: v1
kind: Service
metadata:
  name: {{ .values.AplName }}
spec:
  type: {{ .values.svcType }}
  selector:
    app: {{ .values.AplName }}
  ports:
    - port: {{ .values.Port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      {{- if eq .values.svcType "NodePort" }}
      nodePort: {{ .values.NodePort }}
      {{- end }}
