name: "Teste variables between jobs 1"
permissions:
  contents: read
  packages: read
on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      myVar: ${{ steps.setVar.outputs.value }}
    steps:
      - name: Set Variable
        id: setVar
        run: echo "::set-output name=value::Hello, GitHub!"
        shell: bash

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Variable from Job 1
        run: |
          echo "The variable is: ${{ needs.job1.outputs.myVar }}"